Здесь я смотрю на баланс классов и разбиваю выборку на обучающую и отложенную.

In [34]:
SEED = 42

In [ ]:
import polars as pl

full_dataset = pl.read_csv('../data/processed/dataset_clean_label.csv')

In [36]:
import json

error_type_ids = open('../data/processed/error_type_ids.json',
                      'r', -1, 'utf-8')
error_type_names = {v: k for k, v in json.load(error_type_ids).items()}
error_type_ids.close()

In [37]:
full_dataset\
    .group_by('error_type_label')\
    .len()\
    .with_columns(pl.col('error_type_label')\
                  .replace_strict(error_type_names, default=None)\
                  .alias('error_type_name'))\
    .sort('len', descending=True)

shape: (8, 3)
┌──────────────────┬───────┬─────────────────────────┐
│ error_type_label ┆ len   ┆ error_type_name         │
│ ---              ┆ ---   ┆ ---                     │
│ i64              ┆ u32   ┆ str                     │
╞══════════════════╪═══════╪═════════════════════════╡
│ 0                ┆ 19775 ┆ нет                     │
│ 4                ┆ 1153  ┆ задержка                │
│ 3                ┆ 414   ┆ дизартрия               │
│ 7                ┆ 339   ┆ фонетическая парафазия  │
│ 6                ┆ 185   ┆ семантическая парафазия │
│ 2                ┆ 124   ┆ аномия                  │
│ 5                ┆ 79    ┆ поиск слова             │
│ 1                ┆ 32    ┆ speech arrest           │
└──────────────────┴───────┴─────────────────────────┘

In [41]:
from sklearn.model_selection import train_test_split

dataset_train, dataset_test = train_test_split(full_dataset, 
                            test_size=0.25,
                            stratify=full_dataset['error_type_label'],
                            random_state=SEED)

In [ ]:
dataset_train\
    .group_by('error_type_label')\
    .len()\
    .with_columns(pl.col('error_type_label')\
                  .replace_strict(error_type_names, default=None)\
                  .alias('error_type_name'))\
    .sort('len', descending=True)

shape: (8, 3)
┌──────────────────┬───────┬─────────────────────────┐
│ error_type_label ┆ len   ┆ error_type_name         │
│ ---              ┆ ---   ┆ ---                     │
│ i64              ┆ u32   ┆ str                     │
╞══════════════════╪═══════╪═════════════════════════╡
│ 0                ┆ 14831 ┆ нет                     │
│ 4                ┆ 865   ┆ задержка                │
│ 3                ┆ 310   ┆ дизартрия               │
│ 7                ┆ 254   ┆ фонетическая парафазия  │
│ 6                ┆ 139   ┆ семантическая парафазия │
│ 2                ┆ 93    ┆ аномия                  │
│ 5                ┆ 59    ┆ поиск слова             │
│ 1                ┆ 24    ┆ speech arrest           │
└──────────────────┴───────┴─────────────────────────┘

In [ ]:
dataset_test\
    .group_by('error_type_label')\
    .len()\
    .with_columns(pl.col('error_type_label')\
                  .replace_strict(error_type_names, default=None)\
                  .alias('error_type_name'))\
    .sort('len', descending=True)

shape: (8, 3)
┌──────────────────┬──────┬─────────────────────────┐
│ error_type_label ┆ len  ┆ error_type_name         │
│ ---              ┆ ---  ┆ ---                     │
│ i64              ┆ u32  ┆ str                     │
╞══════════════════╪══════╪═════════════════════════╡
│ 0                ┆ 4944 ┆ нет                     │
│ 4                ┆ 288  ┆ задержка                │
│ 3                ┆ 104  ┆ дизартрия               │
│ 7                ┆ 85   ┆ фонетическая парафазия  │
│ 6                ┆ 46   ┆ семантическая парафазия │
│ 2                ┆ 31   ┆ аномия                  │
│ 5                ┆ 20   ┆ поиск слова             │
│ 1                ┆ 8    ┆ speech arrest           │
└──────────────────┴──────┴─────────────────────────┘

In [45]:
dataset_train.write_csv('../data/processed/train.csv')
dataset_test.write_csv('../data/processed/test.csv')